name: Test suite

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test-static:
    strategy:
      fail-fast: false
      matrix:
        puppet: [5.0, 6.0, 7.0]
        ruby: [2.5.9, 2.6.9]

    name: Static code analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        PUPPET_VERSION: ${{ matrix.puppet }}

    - name: Run metadata lint
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake metadata_lint

    - name: Run puppet lint
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake lint

    - name: Run puppet syntax check
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake syntax

    - name: Run puppet rspec tests
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} STRICT_VARIABLES=yes bundle exec rake spec

    - name: Run rubocop tests
      run: |
        PUPPET_VERSION=${{ matrix.puppet }} bundle exec rake rubocop

  test-integration:
    strategy:
      fail-fast: false
      matrix:
        # puppet: [puppet5, puppet6, puppet7]
        # beakerset: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, centos-7, debian-7, debian-8]
        puppet: [puppet7]
        beakerset: [ubuntu-18.04, ubuntu-20.04]

    name: Integration tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.9
        bundler-cache: true
      env:
        BEAKER_set: ${{ matrix.beakerset }}
        BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
        PUPPET_INSTALL_TYPE: agent

    - name: List tasks
      run: |
        BEAKER_destroy=yes bundle exec rake --tasks
      env:
        BEAKER_set: ${{ matrix.beakerset }}
        BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
        PUPPET_INSTALL_TYPE: agent

    - name: Run puppet-beaker tests
      run: |
        BEAKER_destroy=yes bundle exec rake beaker
      env:
        BEAKER_set: ${{ matrix.beakerset }}
        BEAKER_PUPPET_COLLECTION: ${{ matrix.puppet }}
        PUPPET_INSTALL_TYPE: agent